# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
coordination:
  enabled: true
  serverUrl: "http://localhost:54321"
  socketNamespace: "/dev-coordination"
  autoStartServer: true # Automatically start server if not running
  serverStartTimeout: 10 # seconds to wait for server startup
  developerAuth:
    method: "simple" # simple, token, oauth
    requireAuth: false
  storyClaimTimeout: 3600 # seconds (1 hour)
  progressUpdateInterval: 300 # seconds (5 minutes)
  conflictResolution: "first-claim-wins" # first-claim-wins, priority-based, manual
